/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.sablecc.node;

import compilador.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TFpar extends Token
{
    public TFpar()
    {
        super.setText(")");
    }

    public TFpar(int line, int pos)
    {
        super.setText(")");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFpar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFpar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFpar text.");
    }
}
