/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.compilador.node;

import br.ufs.compilador.analysis.*;

@SuppressWarnings("nls")
public final class TAcol extends Token
{
    public TAcol()
    {
        super.setText("[");
    }

    public TAcol(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAcol(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAcol(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAcol text.");
    }
}
