/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.compilador.node;

import br.ufs.compilador.analysis.*;

@SuppressWarnings("nls")
public final class TComentarioDeLinha extends Token
{
    public TComentarioDeLinha(String text)
    {
        setText(text);
    }

    public TComentarioDeLinha(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComentarioDeLinha(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComentarioDeLinha(this);
    }
}
