/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.compilador.node;

import br.ufs.compilador.analysis.*;

@SuppressWarnings("nls")
public final class TMenorig extends Token
{
    public TMenorig()
    {
        super.setText("<=");
    }

    public TMenorig(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMenorig(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMenorig(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMenorig text.");
    }
}
