/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.compilador.analysis;

import br.ufs.compilador.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTElse(TElse node);
    void caseTIf(TIf node);
    void caseTInt(TInt node);
    void caseTString(TString node);
    void caseTReturn(TReturn node);
    void caseTVoid(TVoid node);
    void caseTWhile(TWhile node);
    void caseTSoma(TSoma node);
    void caseTSub(TSub node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMenorq(TMenorq node);
    void caseTMenorig(TMenorig node);
    void caseTMaiorq(TMaiorq node);
    void caseTMaiorig(TMaiorig node);
    void caseTIgual(TIgual node);
    void caseTNao(TNao node);
    void caseTAtrib(TAtrib node);
    void caseTPtvirg(TPtvirg node);
    void caseTVirg(TVirg node);
    void caseTApar(TApar node);
    void caseTFpar(TFpar node);
    void caseTAcol(TAcol node);
    void caseTFcol(TFcol node);
    void caseTAchave(TAchave node);
    void caseTFchave(TFchave node);
    void caseTId(TId node);
    void caseTNum(TNum node);
    void caseTStringLiteral(TStringLiteral node);
    void caseTEspacosEmBranco(TEspacosEmBranco node);
    void caseTComentarioDeLinha(TComentarioDeLinha node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseTComentarioBlocoFim(TComentarioBlocoFim node);
    void caseTComentarioBlocoCorpo(TComentarioBlocoCorpo node);
    void caseTEstrela(TEstrela node);
    void caseTBarra(TBarra node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
